[package]
name = "searchsms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
chrono = { version = "0.4.23", default-features = false, features = ["std", "clock"] }
env_logger = { version = "0.10.0", default-features = false, features = ["color", "humantime"] }
lexopt = "0.2.1"
log = "0.4.17"
regex = "1.7.0"
roxmltree = "0.16.0"
textwrap = { version = "0.16.0", default-features = false }

[[bin]]
name = "searchsms"
path = "main.rs"
