#!/bin/bash

# Find a valid SSH_AUTH_SOCK and symlink it to a known location. Once it's
# at a known location, other applications like tmux can pick it up and
# automatically reconnect to the correct agent.
for agent in /tmp/ssh-*/agent.*; do
  if SSH_AUTH_SOCK="$agent" ssh-add -L > /dev/null 2>&1; then
    ln -sf "$agent" /tmp/andrew_ssh_auth_sock
  fi
done
