[package]
name = "ppbinary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
bstr = "1.1.0"

[[bin]]
name = "ppbinary"
path = "main.rs"
